#!/usr/bin/env bash

case "$1" in
    docker)
        echo "### building rawrepo-introspect-backend docker ###"
        docker build . --pull --no-cache -t docker-metascrum.artifacts.dbccloud.dk/rawrepo-introspect-backend:devel || exit 1
        if [[ ! -z "$BUILD_NUMBER" ]]; then
            docker tag docker-metascrum.artifacts.dbccloud.dk/rawrepo-introspect-backend:devel docker-metascrum.artifacts.dbccloud.dk/rawrepo-introspect-backend:${BRANCH_NAME}-${BUILD_NUMBER}
        fi
        ;;

    *)
        echo "### building rawrepo-introspect-backend project ###"
        echo "### Look for build artifacts in target/ ###"

        mvn package -Dmaven.test.skip=true || exit 1
        ;;
esac
